### ISSUE TITLE
The class 'org.yougi.entity.AccessGroup' does not have a writable property 'name'

### ISSUE THREAD

**Issue by emanuelmm** [yougi/yougi_groovy#21]
Verifiquei, que após migrar a tela de Grupos esse erro (Caused by: javax.el.PropertyNotWritableException: The class 'org.yougi.entity.AccessGroup' does not have a writable property 'name') está aparencendo. De fato, não verifiquei se já existia esse erro na versão original do Yougi, mas enfim, o erro está lá.
Na entidade AccessGroup tá tudo aparente normal, porém, notei que o método setName não é void. @danielsoro  comentou que isso não deveria ser a causa do problema, mas quando mudei pra void funcionou e passou a dar o mesmo erro para a propriedade id.

Bem, como no README.md, está destacado que apenas os "MBean" estão sendo migrados nesse momento, não posso migrar a entidade para groovy e ver se não seria algum "lance" relacionado com o groovy e java.

**Comment by Gessyca** [comment]
@emanuelmm Na última classe que migrei MailingListMBean aconteceu o mesmo erro com a propriedade ID.

**Comment by danielsoro** [comment]
Gessyca, o erro aconteceu depois da migração!?
Ou o erro já acontecia!?

Essa era a minha dúvida. :)

On Thu, Apr 16, 2015 at 9:16 AM, Gessyca Marques <notifications@github.com>
wrote:

> @emanuelmm <https://github.com/emanuelmm> Na última classe que migrei
> MailingListMBean aconteceu o mesmo erro com a propriedade ID.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yougi/yougi_groovy/issues/21#issuecomment-93719696>.
>



-- 
Best regard,
Daniel Cunha (soro)

**Comment by danielsoro** [comment]
Eu estava a olhar o código do MyFaces (Implementação de JSF da Apache) por
vistas grosas, não me parece que ele verifica se o método é void ou não.

Bom, também olhei o PropertyDescriptor, por vistas grosas, e também não me
pareceu verificar se o método era void.

On Thu, Apr 16, 2015 at 10:33 AM, Daniel Cunha <danielsoro@gmail.com> wrote:

> Gessyca, o erro aconteceu depois da migração!?
> Ou o erro já acontecia!?
>
> Essa era a minha dúvida. :)
>
> On Thu, Apr 16, 2015 at 9:16 AM, Gessyca Marques <notifications@github.com
> > wrote:
>
>> @emanuelmm <https://github.com/emanuelmm> Na última classe que migrei
>> MailingListMBean aconteceu o mesmo erro com a propriedade ID.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/yougi/yougi_groovy/issues/21#issuecomment-93719696>.
>>
>
>
>
> --
> Best regard,
> Daniel Cunha (soro)
>



-- 
Best regard,
Daniel Cunha (soro)

**Comment by Gessyca** [comment]
@danielsoro Já existia.

https://cloud.githubusercontent.com/assets/6443576/7178738/81b54124-e407-11e4-9767-b6a9dda63bec.png

**Comment by danielsoro** [comment]
Ok!

Sendo assim.. será corrigido depois.

On Thu, Apr 16, 2015 at 11:02 AM, Gessyca Marques <notifications@github.com>
wrote:

> @danielsoro <https://github.com/danielsoro> Já existia.
>
>
> https://cloud.githubusercontent.com/assets/6443576/7178738/81b54124-e407-11e4-9767-b6a9dda63bec.png
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yougi/yougi_groovy/issues/21#issuecomment-93742088>.
>



-- 
Best regard,
Daniel Cunha (soro)

**Comment by emanuelmm** [comment]
Ok, sendo assim, vou reenviar o PR, já que ele não foi a causa do problema;

@danielsoro os testes que fiz foi com o Mojarra.

**Comment by eprogramming** [comment]
não tem haver com a implementação ( mojarra ou myfaces ) 
é porque precisa seguir especificação JavaBean.

**Comment by danielsoro** [comment]
Bom,

só se a spec mudou (o que é estranho, já que o java se preocupa com a
retrocompatibilidade), porque olhando os models, 90% dos sets possuim
retorno, sendo assim.. nenhuma página funcionaria desde o inicio.
Isso me soa estranho.

On Thu, Apr 16, 2015 at 11:48 AM, Helio Frota <notifications@github.com>
wrote:

> não tem haver com a implementação ( mojarra ou myfaces )
> é porque precisa seguir especificação JavaBean.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yougi/yougi_groovy/issues/21#issuecomment-93753156>.
>



-- 
Best regard,
Daniel Cunha (soro)

**Comment by eprogramming** [comment]
@danielsoro veja na lista da esmeril, eu corrigi esse problema com o CRUD de países.
@emanuelmm thanks pelo issue

dica: discussão-- código++

**Comment by danielsoro** [comment]
Ok.
