### ISSUE TITLE
Add @CompileStatic to all classes

### ISSUE THREAD

**Issue by eprogramming** [yougi/yougi_groovy#50]
we will not modify code at runtime, we will always do a deploy in wildfly, so we need to use @CompileStatic 

@burtbeckwith thanks for this explanation:

> Groovy is a dynamic language and by default Groovy uses a dynamic dispatch mechanism to carry out method calls and property access. ... it is possible to dynamically add methods to classes at runtime and it is possible to dynamically replace existing methods at runtime. .. However, there are times when you may want to disable this dynamic dispatch in favor of a more static dispatch mechanism... The way to tell the Groovy compiler that a particular class should compiled statically is to mark the class with the groovy.transform.CompileStatic annotation

http://grails.github.io/grails-doc/2.4.0/guide/staticTypeCheckingAndCompilation.html

**Comment by htmfilho** [comment]
Does it have any impact on performance?

**Comment by eprogramming** [comment]
yup

>our custom processor is written in Groovy, and for better compilation performance, we use static compilation

http://groovy-lang.org/single-page-documentation.html
